### ISSUE TITLE
lein / boot / mvn plugin support?

### ISSUE THREAD

**Issue by stuarthalloway** [cognitect-labs/transcriptor#2]

**Comment by stuarthalloway** [comment]
I have used transcriptor from lein, boot, and mvn projects without any problem. I don't have a personal interest in developing or maintaining build tool plugins, but would be happy to see others do so.

If you don't have preexisting commitments to lein, boot, or mvn tooling, Clojure's own command line tooling is simpler and more in keeping with the philosophy behind transcriptor: https://clojure.org/guides/deps_and_cli.

**Comment by Olical** [comment]
Here's a lein version :) https://github.com/Olical/lein-transcriptor
