### ISSUE TITLE
Potential ClojureScript support

### ISSUE THREAD

**Issue by Olical** [cognitect-labs/transcriptor#3]
I _think_ it's possible with self hosted ClojureScript within node or a similar runtime. That would allow you to test simple user interfaces in the same way through something like `jsdom` (a mock DOM data structure without a browser).

I was going to have a go at this, but wanted to place an issue here first since it may not be the right thing to do. If it doesn't fit within the philosophy of transcriptor then that's fine.

I was planning on converting over to a `.cljc` file so you could `:require` transcriptor from a Clojure or ClojureScript namespace in the exact same way.

**Comment by stuarthalloway** [comment]
I remember seeing a conversation about ClojureScript somewhere and now cannot find it.  Is a simple rename to .cljc sufficient here?

**Comment by Olical** [comment]
I think it was actually quite a bit more involved last time I checked because of JVM specific code. I doubt it'd be too hard, but it'd probably be cleaner to just write a version in a `.cljs` file that did the exact same thing but using `node` as a runtime.

I'll try to work out what a `.cljc` would look like for this soon, if you're happy to leave this issue open a while longer. If it would be extremely messy with a lot of reader conditionals it's probably best to either leave it or start a fresh `.cljs`.

**Comment by Olical** [comment]
Going to close this to remove the annoying (1) from your issues tab. I won't be getting around to this, it's a big chunk of work really, the two worlds are very different.
